# Define 9R Framework keywords

class Keywords():
  
    re_strategies = {
    "R0": {
        "name": "Refuse",
        "definition": "Avoid the use of products and materials that are not necessary or that generate waste. This focuses on prevention by refusing to use non-essential products."
    },
    "R1": {
        "name": "Rethink",
        "definition": "Reconsider the way products are used and designed to maximize efficiency, reduce resource consumption, and improve sustainability. Often involves innovative approaches."
    },
    "R2": {
        "name": "Reduce",
        "definition": "Minimize the amount of resources used in the production process and the waste generated by using more efficient methods or alternatives."
    },
    "R3": {
        "name": "Reuse",
        "definition": "Extend the life of products or materials by using them multiple times, either in their original form or with minor repairs or modifications."
    },
    "R4": {
        "name": "Repair",
        "definition": "Fix damaged or worn-out products to extend their lifecycle instead of discarding them, reducing the need for new resources."
    },
    "R5": {
        "name": "Refurbish",
        "definition": "Restore and improve used products to a like-new condition, often involving repairs, updates, and cleaning to prepare them for reuse."
    },
    "R6": {
        "name": "Remanufacture",
        "definition": "Disassemble a product and restore its components to a like-new condition to be reused, often involving quality checks and the replacement of certain parts."
    },
    "R7": {
        "name": "Repurpose",
        "definition": "Use products or materials for a different purpose than they were originally intended, often without significant alteration."
    },
    "R8": {
        "name": "Recycle",
        "definition": "Process used materials to create new products or raw materials, preventing waste and reducing the demand for virgin resources."
    },
    "R9": {
        "name": "Recover",
        "definition": "Extract useful materials or energy from waste products, often through processes like energy recovery or material recovery from discarded products."
    }
}
