# Define 9R Framework keywords

class Keywords():
  
    re_strategies = {
    "R0": {
        "name": "Refuse",
        "definition": "Avoid the use of products and materials that are not necessary or that generate waste. This focuses on prevention by refusing to use non-essential products."
    },
    "R1": {
        "name": "Rethink",
        "definition": "Reconsider the way products are used and designed to maximize efficiency, reduce resource consumption, and improve sustainability. Often involves innovative approaches."
    },
    "R2": {
        "name": "Reduce",
        "definition": "Minimize the amount of resources used in the production process and the waste generated by using more efficient methods or alternatives."
    },
    "R3": {
        "name": "Reuse",
        "definition": "Extend the life of products or materials by using them multiple times, either in their original form or with minor repairs or modifications."
    },
    "R4": {
        "name": "Repair",
        "definition": "Fix damaged or worn-out products to extend their lifecycle instead of discarding them, reducing the need for new resources."
    },
    "R5": {
        "name": "Refurbish",
        "definition": "Restore and improve used products to a like-new condition, often involving repairs, updates, and cleaning to prepare them for reuse."
    },
    "R6": {
        "name": "Remanufacture",
        "definition": "Disassemble a product and restore its components to a like-new condition to be reused, often involving quality checks and the replacement of certain parts."
    },
    "R7": {
        "name": "Repurpose",
        "definition": "Use products or materials for a different purpose than they were originally intended, often without significant alteration."
    },
    "R8": {
        "name": "Recycle",
        "definition": "Process used materials to create new products or raw materials, preventing waste and reducing the demand for virgin resources."
    },
    "R9": {
        "name": "Recover",
        "definition": "Extract useful materials or energy from waste products, often through processes like energy recovery or material recovery from discarded products."
    }
}


    re_strategies_2 = {
    "R0": "Recycle",
    "R1": "Reduce",
    "R2": "Renew",
    "R3": "Reuse",
    "R4": "Recover",
    "R5": "Regenerate",
    "R6": "Return",
    "R7": "Repair",
    "R8": "Refurbish",
    "R9": "Rent",
    "R10": "Replace",
    "R11": "Remove",
    "R12": "Restore",
    "R13": "Repurpose",
    "R14": "Refine",
    "R15": "Rethink",
    "R16": "Redesign",
    "R17": "Resell - Resale",
    "R18": "React",
    "R19": "Remanufacture",
    "R20": "Reclaim",
    "R21": "Renovate",
    "R22": "Reprocess",
    "R23": "Reinvent",
    "R24": "Redefine",
    "R25": "Reinforce",
    "R26": "Recommerce",
    "R27": "Refill",
    "R28": "Remarket",
    "R29": "Redistribute",
    "R30": "Recreate",
    "R31": "Reform",
    "R32": "Reshape",
    "R33": "Repeat",
    "R34": "Recirculate",
    "R35": "Recondition",
    "R36": "Reforestate",
    "R37": "Restructure",
    "R38": "Relocate",
    "R39": "Remake",
    "R40": "Resolve",
    "R41": "Rehabilitate",
    "R42": "Reconnect",
    "R43": "Re-engineer",
    "R44": "Reset",
    "R45": "Reutilize",
    "R46": "Rebrand",
    "R47": "Reskill",
    "R48": "Revalue",
    "R49": "Redeploy",
    "R50": "Redevelop",
    "R51": "Repack",
    "R52": "Recharge",
    "R53": "Rework",
    "R54": "Revalorize",
    "R55": "Regrind",
    "R56": "Reorganize",
    "R57": "Remodel",
    "R58": "Refashion",
    "R59": "Regreen",
    "R60": "Reconstruct",
    "R61": "Revert",
    "R62": "Readapt",
    "R63": "Rebanner",
    "R64": "Recultivate",
    "R65": "Refurnish",
    "R66": "Rewild",
    "R67": "Reprogram"
}
