# Define 9R Framework keywords

class Keywords():
    nine_r_keywords = {
        "Refuse": ["eliminate", "avoid", "ban", "reject", "prohibit", "forego", "decline", "disallow", "abstain"],
        "Rethink": ["rethink", "reconsider", "reimagine", "innovate", "transform", "optimize", "repurpose", "shift"],
        "Reduce": ["reduce", "cut down", "decrease", "minimize", "lower", "lessen", "conserve", "diminish", "trim"],
        "Reuse": ["reuse", "repurpose", "second-hand", "reutilize", "reapply", "salvage", "reclaim", "upcycle", "redeploy"],
        "Repair": ["repair", "fix", "mend", "restore", "refurbish", "rectify", "patch", "rehabilitate"],
        "Refurbish": ["refurbish", "renovate", "overhaul", "restore", "revamp", "update", "recondition", "upgrade", "renew"],
        "Remanufacture": ["remanufacture", "rebuild", "reconstruct", "reengineer", "reassemble", "reproduce", "fabricate", "renovate"],
        "Repurpose": ["repurpose", "transform", "adapt", "convert", "redesign", "redeploy", "reinvent", "change", "refashion"],
        "Recycle": ["recycle", "process", "convert", "reprocess", "reconstitute", "reclaim", "re-utilize", "transform"],
        "Recover": ["recover", "extract", "reclaim", "retrieve", "salvage", "gain", "recuperate", "regain"]
    }

    nine_r_descriptions = {
        "Refuse": "Start-ups that eliminate the use of resources entirely. Examples: Digital services replacing physical products.",
        "Rethink": "Start-ups that use products more intensively. Examples: Shared economy models, product-as-a-service.",
        "Reduce": "Start-ups that minimize resource use in production. Examples: Lean manufacturing, resource-efficient production.",
        "Reuse": "Start-ups that allow products to be reused by others. Examples: Second-hand platforms, repair services.",
        "Repair": "Start-ups that repair products to extend their lifespan. Examples: Repair cafés, refurbishing services.",
        "Refurbish": "Start-ups that restore products to good condition. Examples: Electronics refurbishers, furniture restoration.",
        "Remanufacture": "Start-ups that produce new products from used components. Examples: Automotive parts remanufacturing.",
        "Repurpose": "Start-ups that use discarded products or components for new purposes. Examples: Upcycling initiatives.",
        "Recycle": "Start-ups that process materials to obtain new raw materials. Examples: Plastic recycling, metal recycling.",
        "Recover": "Start-ups that recover energy from waste. Examples: Waste-to-energy plants."
    }

    # Define Business Model Types keywords and descriptions
    business_model_keywords = {
        "Circular Supply Chain": ["supply", "sustainable", "renewable", "biodegradable", "eco-friendly", "green", "resource-efficient", "organic", "natural"],
        "Resource Recovery": ["recover", "recycle", "reclaim", "repurpose", "salvage", "extract", "reutilize", "retrieve"],
        "Product Life Extension": ["extend", "lifespan", "durability", "maintenance", "refurbish", "longevity", "repair", "update", "upgrade"],
        "Sharing Platforms": ["share", "rent", "lease", "co-use", "access", "borrow", "collaborative", "peer-to-peer"],
        "Product as a Service": ["service", "subscription", "lease", "rental", "usage", "pay-per-use", "access", "hire"]
    }

    # Define descriptions for each Business Model Types category
    business_model_descriptions = {
        "Circular Supply Chain": "Start-ups that provide renewable, recyclable, or biodegradable resources. Examples: Suppliers of sustainable materials.",
        "Resource Recovery": "Start-ups focused on recovering and repurposing end-of-life products. Examples: Recycling companies, waste management firms.",
        "Product Life Extension": "Start-ups that extend the lifecycle of products. Examples: Maintenance services, refurbishment businesses.",
        "Sharing Platforms": "Start-ups that facilitate the sharing of underutilized assets. Examples: Car-sharing services, tool lending libraries.",
        "Product as a Service": "Start-ups offering products as services rather than selling them. Examples: Subscription-based models, leasing services."
    }

    circular_economy_res = {
        "Recycle": ["recycle", "recycled", "recyclable"],
        "Reduce": ["reduce", "reduced", "reducing"],
        "Renew": ["renew", "renewable"],
        "Reuse": ["reuse", "reused", "reusable", "reusability"],
        "Recover": ["recover", "recovered", "recovery"],
        "Regenerate": ["regenerate", "regenerated", "regeneration"],
        "Return": ["return"],
        "Repair": ["repair", "repaired", "repairing"],
        "Refurbish": ["refurbish", "refurbished", "refurbishing"],
        "Rent": ["rent", "rented", "renting"],
        "Replace": ["replace", "replaced", "replacing"],
        "Remove": ["remove", "removed", "removing"],
        "Restore": ["restore", "restored", "restoring"],
        "Repurpose": ["repurpose", "repurposed", "repurposing"],
        "Refine": ["refine", "refined", "refining"],
        "Rethink": ["rethink", "rethinking"],
        "Redesign": ["redesign", "redesigned", "redesigning"],
        "Resell": ["resell", "resale", "reselling"],
        "React": ["react", "reacting", "reaction"],
        "Remanufacture": ["remanufacture", "remanufactured", "remanufacturing"],
        "Reclaim": ["reclaim", "reclaimed", "reclaiming"],
        "Renovate": ["renovate", "renovated", "renovating"],
        "Reprocess": ["reprocess", "reprocessed", "reprocessing"],
        "Reinvent": ["reinvent", "reinvented", "reinventing"],
        "Redefine": ["redefine", "redefined", "redefining"],
        "Reinforce": ["reinforce", "reinforced", "reinforcing"],
        "Recommerce": ["recommerce"],
        "Refill": ["refill", "refilled", "refilling"],
        "Remarket": ["remarket", "remarketing"],
        "Redistribute": ["redistribute", "redistributed", "redistributing"],
        "Recreate": ["recreate", "recreated", "recreating"],
        "Reform": ["reform", "reformed", "reforming"],
        "Reshape": ["reshape", "reshaped", "reshaping"],
        "Repeat": ["repeat", "repeated", "repeating"],
        "Recirculate": ["recirculate", "recirculated", "recirculating"],
        "Recondition": ["recondition", "reconditioned", "reconditioning"],
        "Restructure": ["restructure", "restructured", "restructuring"],
        "Relocate": ["relocate", "relocated", "relocating"],
        "Remake": ["remake", "remade", "remaking"],
        "Resolve": ["resolve", "resolved", "resolving"],
        "Reconnect": ["reconnect", "reconnected", "reconnecting"],
        "Re-engineer": ["re-engineer", "re-engineered", "re-engineering"],
        "Reset": ["reset", "resetting"],
        "Reutilize": ["reutilize", "reutilized", "reutilizing"]
    }

    re_strategies_1 = {
    "R0": "Reduce",
    "R1": "Reuse",
    "R2": "Recycle",
    "R3": "Repair",
    "R4": "Remanufacture",
    "R5": "Resell",
    "R6": "Resale",
    "R7": "Rent",
    "R8": "Return",
    "R9": "Refurbish",
    "R10": "Repurpose",
    "R11": "Rethink",
    "R12": "Regenerate",
    "R13": "Refine",
    "R14": "Recover",
    "R15": "Remove",
    "R16": "React",
    "R17": "Reclaim",
    "R18": "Redesign",
    "R19": "Replace",
    "R20": "Restore"
}


    re_strategies = {
    "R0": "Recycle",
    "R1": "Reduce",
    "R2": "Renew",
    "R3": "Reuse",
    "R4": "Recover",
    "R5": "Regenerate",
    # "R6": "Return",
    "R7": "Repair",
    "R8": "Refurbish",
    # "R9": "Rent",
    "R10": "Replace",
    "R11": "Remove",
    "R12": "Restore",
    "R13": "Repurpose",
    "R14": "Refine",
    "R15": "Rethink",
    "R16": "Redesign",
    "R17": "Resell - Resale",
    "R18": "React",
    "R19": "Remanufacture",
    "R20": "Reclaim",
    "R21": "Renovate",
    "R22": "Reprocess",
    "R23": "Reinvent",
    "R24": "Redefine",
    "R25": "Reinforce",
    "R26": "Recommerce",
    "R27": "Refill",
    "R28": "Remarket",
    "R29": "Redistribute",
    "R30": "Recreate",
    "R31": "Reform",
    "R32": "Reshape",
    "R33": "Repeat",
    "R34": "Recirculate",
    "R35": "Recondition",
    "R36": "Reforestate",
    "R37": "Restructure",
    "R38": "Relocate",
    "R39": "Remake",
    "R40": "Resolve",
    "R41": "Rehabilitate",
    "R42": "Reconnect",
    "R43": "Re-engineer",
    "R44": "Reset",
    "R45": "Reutilize",
    "R46": "Rebrand",
    "R47": "Reskill",
    "R48": "Revalue",
    "R49": "Redeploy",
    "R50": "Redevelop",
    "R51": "Repack",
    "R52": "Recharge",
    "R53": "Rework",
    "R54": "Revalorize",
    "R55": "Regrind",
    "R56": "Reorganize",
    "R57": "Remodel",
    "R58": "Refashion",
    "R59": "Regreen",
    "R60": "Reconstruct",
    "R61": "Revert",
    "R62": "Readapt",
    "R63": "Rebanner",
    "R64": "Recultivate",
    "R65": "Refurnish",
    "R66": "Rewild",
    "R67": "Reprogram"
}
