# Define 9R Framework keywords and Circular Economy Re-strategies

class Keywords():
    nine_r_keywords = {
        "Refuse": ["eliminate", "avoid", "ban", "reject", "prohibit", "forego", "decline", "disallow", "abstain"],
        "Rethink": ["rethink", "reconsider", "reimagine", "innovate", "transform", "optimize", "repurpose", "shift"],
        "Reduce": ["reduce", "cut down", "decrease", "minimize", "lower", "lessen", "conserve", "diminish", "trim"],
        "Reuse": ["reuse", "repurpose", "second-hand", "reutilize", "reapply", "salvage", "reclaim", "upcycle", "redeploy"],
        "Repair": ["repair", "fix", "mend", "restore", "refurbish", "rectify", "patch", "rehabilitate"],
        "Refurbish": ["refurbish", "renovate", "overhaul", "restore", "revamp", "update", "recondition", "upgrade", "renew"],
        "Remanufacture": ["remanufacture", "rebuild", "reconstruct", "reengineer", "reassemble", "reproduce", "fabricate", "renovate"],
        "Repurpose": ["repurpose", "transform", "adapt", "convert", "redesign", "redeploy", "reinvent", "change", "refashion"],
        "Recycle": ["recycle", "process", "convert", "reprocess", "reconstitute", "reclaim", "re-utilize", "transform"],
        "Recover": ["recover", "extract", "reclaim", "retrieve", "salvage", "gain", "recuperate", "regain"]
    }

    circular_economy_res = {
        "Recycle": ["recycle", "recycled", "recyclable"],
        "Reduce": ["reduce", "reduced", "reducing"],
        "Renew": ["renew", "renewable"],
        "Reuse": ["reuse", "reused", "reusable", "reusability"],
        "Recover": ["recover", "recovered", "recovery"],
        "Regenerate": ["regenerate", "regenerated", "regeneration"],
        "Return": ["return"],
        "Repair": ["repair", "repaired", "repairing"],
        "Refurbish": ["refurbish", "refurbished", "refurbishing"],
        "Rent": ["rent", "rented", "renting"],
        "Replace": ["replace", "replaced", "replacing"],
        "Remove": ["remove", "removed", "removing"],
        "Restore": ["restore", "restored", "restoring"],
        "Repurpose": ["repurpose", "repurposed", "repurposing"],
        "Refine": ["refine", "refined", "refining"],
        "Rethink": ["rethink", "rethinking"],
        "Redesign": ["redesign", "redesigned", "redesigning"],
        "Resell": ["resell", "resale", "reselling"],
        "React": ["react", "reacting", "reaction"],
        "Remanufacture": ["remanufacture", "remanufactured", "remanufacturing"],
        "Reclaim": ["reclaim", "reclaimed", "reclaiming"],
        "Renovate": ["renovate", "renovated", "renovating"],
        "Reprocess": ["reprocess", "reprocessed", "reprocessing"],
        "Reinvent": ["reinvent", "reinvented", "reinventing"],
        "Redefine": ["redefine", "redefined", "redefining"],
        "Reinforce": ["reinforce", "reinforced", "reinforcing"],
        "Recommerce": ["recommerce"],
        "Refill": ["refill", "refilled", "refilling"],
        "Remarket": ["remarket", "remarketing"],
        "Redistribute": ["redistribute", "redistributed", "redistributing"],
        "Recreate": ["recreate", "recreated", "recreating"],
        "Reform": ["reform", "reformed", "reforming"],
        "Reshape": ["reshape", "reshaped", "reshaping"],
        "Repeat": ["repeat", "repeated", "repeating"],
        "Recirculate": ["recirculate", "recirculated", "recirculating"],
        "Recondition": ["recondition", "reconditioned", "reconditioning"],
        "Restructure": ["restructure", "restructured", "restructuring"],
        "Relocate": ["relocate", "relocated", "relocating"],
        "Remake": ["remake", "remade", "remaking"],
        "Resolve": ["resolve", "resolved", "resolving"],
        "Reconnect": ["reconnect", "reconnected", "reconnecting"],
        "Re-engineer": ["re-engineer", "re-engineered", "re-engineering"],
        "Reset": ["reset", "resetting"],
        "Reutilize": ["reutilize", "reutilized", "reutilizing"]
    }